indicators:
  - key: "ME_Vaccines_Age"
    description: "ME_Vaccines_Age_label"
    indicatorQuery: "SELECT vaccines.name,
                     CASE
                        WHEN round(julianday('now')-julianday(ec_client.dob)) > 364.0 THEN 'Over_1'
                        WHEN round(julianday('now')-julianday(ec_client.dob)) < 365.0 THEN 'Under_1'
                        ELSE 'Null'
                        END age, count(*)
                    FROM vaccines
                    INNER JOIN ec_client
                    ON vaccines.base_entity_id = ec_client.base_entity_id
                    WHERE vaccines.date >= round((julianday(strftime('%Y-%m-%d', '%s', 'utc')) - 2440587.5) * 86400.0 * 1000)
                    AND vaccines.date < round((julianday(strftime('%Y-%m-%d', '%s', '+1 day', 'utc')) - 2440587.5) * 86400.0 * 1000)
                    AND vaccines.child_location_id = vaccines.location_id OR vaccines.child_location_id IS NULL
                    AND ec_client.dob >= date('now', '-5 years')
                    AND '%s' = date(vaccines.date/1000, 'unixepoch', 'localtime')
                     AND ec_client.is_closed !=1
                    GROUP BY vaccines.name, age"
    isMultiResult: true
    expectedIndicators:
      - "ME_Vaccines_Age_bcg_Over_1"
      - "ME_Vaccines_Age_bcg_Under_1"
      - "ME_Vaccines_Age_opv_0_Over_1"
      - "ME_Vaccines_Age_opv_0_Under_1"
      - "ME_Vaccines_Age_opv_1_Over_1"
      - "ME_Vaccines_Age_opv_1_Under_1"
      - "ME_Vaccines_Age_opv_2_Over_1"
      - "ME_Vaccines_Age_opv_2_Under_1"
      - "ME_Vaccines_Age_opv_3_Over_1"
      - "ME_Vaccines_Age_opv_3_Under_1"
      - "ME_Vaccines_Age_penta_1_Over_1"
      - "ME_Vaccines_Age_penta_1_Under_1"
      - "ME_Vaccines_Age_penta_2_Over_1"
      - "ME_Vaccines_Age_penta_2_Under_1"
      - "ME_Vaccines_Age_penta_3_Over_1"
      - "ME_Vaccines_Age_penta_3_Under_1"
      - "ME_Vaccines_Age_pcv_1_Over_1"
      - "ME_Vaccines_Age_pcv_1_Under_1"
      - "ME_Vaccines_Age_pcv_2_Over_1"
      - "ME_Vaccines_Age_pcv_2_Under_1"
      - "ME_Vaccines_Age_pcv_3_Over_1"
      - "ME_Vaccines_Age_pcv_3_Under_1"
      - "ME_Vaccines_Age_rota_1_Over_1"
      - "ME_Vaccines_Age_rota_1_Under_1"
      - "ME_Vaccines_Age_rota_2_Over_1"
      - "ME_Vaccines_Age_rota_2_Under_1"
      - "ME_Vaccines_Age_mv_1_Over_1"
      - "ME_Vaccines_Age_mv_1_Under_1"
      - "ME_Vaccines_Age_mv_2_Over_1"
      - "ME_Vaccines_Age_mv_2_Under_1"
      - "ME_Vaccines_Age_mv_3_Over_1"
      - "ME_Vaccines_Age_mv_3_Under_1"
      - "ME_Vaccines_Age_mv_4_Over_1"
      - "ME_Vaccines_Age_measles_1_/_mr_1_Over_1"
      - "ME_Vaccines_Age_measles_1_/_mr_1_Under_1"
      - "ME_Vaccines_Age_ipv_Over_1"
      - "ME_Vaccines_Age_ipv_Under_1"
    grouping: "child"

  - key: "ME_Fully_Immunized_Static"
    description: "Fully Immunized"
    indicatorQuery: "SELECT age,count(*) from (select
                     CASE
                           WHEN round(julianday('now')-julianday(ec_client.dob)) > 365.0 THEN 'Over_1'
                           WHEN round(julianday('now')-julianday(ec_client.dob)) < 365.0 THEN 'Under_1'
                           ELSE 'Null'
                           END age,count(*)
                     from vaccines
                     join ec_client
                     on vaccines.base_entity_id = ec_client.base_entity_id
                     where '%s' = date(vaccines.date/1000, 'unixepoch', 'localtime')
                     AND ec_client.is_closed !=1
                     and (vaccines.child_location_id=vaccines.location_id OR vaccines.child_location_id IS NULL)
                     group by vaccines.base_entity_id,age
                     having sum(case when name = 'bcg' then 1 else 0 end) > 0
                     and sum(case when name = 'ipv' then 1 else 0 end) > 0
                     and sum(case when name = 'mr_1' then 1 else 0 end) > 0
                     and sum(case when name = 'opv_1' then 1 else 0 end) > 0
                     and sum(case when name = 'opv_3' then 1 else 0 end) > 0
                     and sum(case when name = 'pcv_1' then 1 else 0 end) > 0
                     and sum(case when name = 'penta_1' then 1 else 0 end) > 0
                     and sum(case when name = 'penta_2' then 1 else 0 end) > 0
                     and sum(case when name = 'penta_3' then 1 else 0 end) > 0
                     and sum(case when name = 'rota_1' then 1 else 0 end) > 0)
                     UNION SELECT 'Monthly_Target' ,count(*)-1"
    isMultiResult: true
    expectedIndicators:
      - "ME_Fully_Immunized_Static_Monthly_Target"
      - "ME_Fully_Immunized_Static_Over_1"
      - "ME_Fully_Immunized_Static_Under_1"
    grouping: "child"

  - key: "ME_VitA_Age_Static"
    description: "ME Vit A"
    indicatorQuery: "SELECT recur_type.name,
                     CASE
                          WHEN round(julianday('now')-julianday(ec_client.dob)) > 364.0 THEN 'Over_1'
                          WHEN round(julianday('now')-julianday(ec_client.dob)) < 365.0 THEN 'Under_1'
                          ELSE 'Null'
                          END age, count(*) counter
                     FROM recurring_service_records recur
                     INNER JOIN ec_client
                     ON recur.base_entity_id = ec_client.base_entity_id
                     JOIN recurring_service_types recur_type
                     ON recur_type._id = recur.recurring_service_id
                     WHERE recur.date >= round((julianday(strftime('%Y-%m-%d', '%s', 'utc')) - 2440587.5) * 86400.0 * 1000)
                     AND recur.date < round((julianday(strftime('%Y-%m-%d', '%s', '+1 day', 'utc')) - 2440587.5) * 86400.0 * 1000)
                     AND ec_client.dob >= date('now', '-5 years')
                     AND (recur.child_location_id=recur.location_id OR recur.child_location_id IS NULL)
                     AND recur_type.name IN ('Vit_A_1', 'Vit_A_2')
                     AND '%s' = date(recur.date/1000, 'unixepoch', 'localtime')
                     AND ec_client.is_closed !=1
                     GROUP BY type,age"
    isMultiResult: true
    expectedIndicators:
      - "ME_VitA_Age_Static_Vit_A_1_Under_1_Male"
      - "ME_VitA_Age_Static_Vit_A_1_Over_1_Male"
      - "ME_VitA_Age_Static_Vit_A_2_Over_1_Male"
    grouping: "child"

  ##OPD Reports
#  - key: "ME_Waiting_List"
#    description: "Waiting_List"
#    indicatorQuery: "SELECT
#                      CASE
#                          WHEN round(julianday('now') - julianday(ec_client.dob)) > 18270 THEN 'Over_50'
#                          WHEN round(julianday('now') - julianday(ec_client.dob)) <= 18270 THEN 'Under_50'
#                          ELSE 'Null'
#                      END age, count(*)
#                      FROM opd_covid19_waiting_list b
#                      INNER JOIN ec_client
#                      ON b.base_entity_id = ec_client.base_entity_id
#                      WHERE b.waiting_list = '1'
#                      and '%s' = strftime('%Y-%m-%d', b.created_at)
#                      GROUP  BY age"
#    isMultiResult: true
#    expectedIndicators:
#      - "ME_Waiting_List_Over_50"
#      - "ME_Waiting_List_Under_50"
#    grouping: "opd"

  - key: "ME_Covid19_Vaccines_Age_Azoxford"
    description: "Covid19_Vaccines_Age_Azoxford"
    indicatorQuery: "SELECT
                      CASE
                          WHEN round(julianday('now') - julianday(ec_client.dob)) > 18270 THEN 'Over_50'
                          WHEN round(julianday('now') - julianday(ec_client.dob)) <= 18270 THEN 'Under_50'
                          ELSE 'Null'
                      END age, count(*)
                      FROM opd_covid19_vaccine_administration b
                      INNER JOIN ec_client
                      ON b.base_entity_id = ec_client.base_entity_id
                      WHERE b.covid19_antigens = 'az_oxford'
                      AND '%s' = strftime('%Y-%m-%d', b.created_at)
                      GROUP BY age"
    isMultiResult: true
    expectedIndicators:
      - "ME_Covid19_Vaccines_Age_Azoxford_Over_50"
      - "ME_Covid19_Vaccines_Age_Azoxford_Under_50"
    grouping: "opd"

  - key: "ME_Covid19_Vaccines_Age_Sinovac"
    description: "Covid19_Vaccines_Age_Sinovac"
    indicatorQuery: "SELECT
                    CASE
                        WHEN round(julianday('now') - julianday(ec_client.dob)) > 18270 THEN 'Over_50'
                        WHEN round(julianday('now') - julianday(ec_client.dob)) <= 18270 THEN 'Under_50'
                        ELSE 'Null'
                    END age, count(*)
                    FROM opd_covid19_vaccine_administration b
                    INNER JOIN ec_client
                    ON b.base_entity_id = ec_client.base_entity_id
                    WHERE b.covid19_antigens = 'sinovac'
                    AND '%s' = strftime('%Y-%m-%d', b.created_at)
                    GROUP BY age"
    isMultiResult: true
    expectedIndicators:
      - "ME_Covid19_Vaccines_Age_Sinovac_Over_50"
      - "ME_Covid19_Vaccines_Age_Sinovac_Under_50"
    grouping: "opd"

  - key: "ME_Covid19_Vaccines_Age_Sinopharm"
    description: "Covid19_Vaccines_Age_Sinopharm"
    indicatorQuery: "SELECT
                    CASE
                        WHEN round(julianday('now') - julianday(ec_client.dob)) > 18270 THEN 'Over_50'
                        WHEN round(julianday('now') - julianday(ec_client.dob)) <= 18270 THEN 'Under_50'
                        ELSE 'Null'
                    END age, count(*)
                    FROM opd_covid19_vaccine_administration b
                    INNER JOIN ec_client
                    ON b.base_entity_id = ec_client.base_entity_id
                    WHERE b.covid19_antigens = 'sinopharm'
                    AND '%s' = strftime('%Y-%m-%d', b.created_at)
                    GROUP BY age"
    isMultiResult: true
    expectedIndicators:
      - "ME_Covid19_Vaccines_Age_Sinopharm_Over_50"
      - "ME_Covid19_Vaccines_Age_Sinopharm_Under_50"
    grouping: "opd"

#  - key: "ME_Total_Client_On_Waiting_List"
#    description: "Total Clients in Waiting List"
#    indicatorQuery: "SELECT COUNT(*) from opd_covid19_waiting_list WHERE opd_covid19_waiting_list.waiting_list = '1' AND '%s' = strftime('%Y-%m-%d', opd_covid19_waiting_list.created_at)"
#    grouping: "opd"
#
#  - key: "ME_Total_Vaccines_Given"
#    description: "Total Vaccines Given"
#    indicatorQuery: "SELECT COUNT(*) from opd_covid19_vaccine_administration WHERE '%s' = strftime('%Y-%m-%d', opd_covid19_vaccine_administration.created_at)"
#    grouping: "opd"


# Influenza

  - key: "ME_Influenza_Age_Static"
    description: "ME Vit A"
    indicatorQuery: "SELECT recur_type.name,
                       CASE
                            WHEN round(julianday('now')-julianday(ec_client.dob)) > 364.0 THEN 'Over_1'
                            WHEN round(julianday('now')-julianday(ec_client.dob)) < 365.0 THEN 'Under_1'
                            ELSE 'Null'
                            END age, ec_client.gender, count(*) counter
                       FROM recurring_service_records recur
                       INNER JOIN ec_client
                       ON recur.base_entity_id = ec_client.base_entity_id
                       JOIN recurring_service_types recur_type
                       ON recur_type._id = recur.recurring_service_id
                       WHERE recur.date >= round((julianday(strftime('%Y-%m-%d', '%s', 'utc')) - 2440587.5) * 86400.0 * 1000)
                       AND recur.date < round((julianday(strftime('%Y-%m-%d', '%s', '+1 day', 'utc')) - 2440587.5) * 86400.0 * 1000)
                       AND ec_client.dob >= date('now', '-5 years')
                       AND (recur.child_location_id=recur.location_id OR recur.child_location_id IS NULL)
                       AND recur_type.name IN ('Vit_A_1', 'Vit_A_2')
                       AND '%s' = date(recur.date/1000, 'unixepoch', 'localtime')
                       AND ec_client.is_closed !=1
                       GROUP BY type,age,gender"
    isMultiResult: true
    expectedIndicators:
      - "ME_VitA_Age_Static_Vit_A_1_Under_1_Male"
      - "ME_VitA_Age_Static_Vit_A_1_Under_1_Female"
      - "ME_VitA_Age_Static_Vit_A_1_Over_1_Male"
      - "ME_VitA_Age_Static_Vit_A_1_Over_1_Female"
      - "ME_VitA_Age_Static_Vit_A_2_Over_1_Male"
      - "ME_VitA_Age_Static_Vit_A_2_Over_1_Female"
    grouping: "child"